### ISSUE TITLE
[错误] 下载失败 : php-5.6.5.tar.gz, 请检查 http://u1.cdn.yuxiaoxi.com/linux/amh-4.2/php-5.6.5.tar.gz 

### ISSUE THREAD

**Issue by jarvanh** [maicong/amh-4.2#1]
[错误] 下载失败 : php-5.6.5.tar.gz, 请检查 http://u1.cdn.yuxiaoxi.com/linux/amh-4.2/php-5.6.5.tar.gz

**Comment by maicong** [comment]
... 我看看

**Comment by Jarvanh** [comment]
一会行一会不行，可能是网络的问题

**Comment by maicong** [comment]
试试最新的？

**Comment by septs** [comment]
使用rawgit.com的CDN服务可以获得更好的体验
修改比较简单
https://github.com/maicong/amh-4.2/blob/master/amh-mc.sh#L29
修改为：

```
GetUrl='https://cdn.rawgit.com/maicong/amh-4.2/master';
```

就可以啦

**Comment by maicong** [comment]
嗯，明天我把国内外的cdn地址一起补上

**Comment by Jarvanh** [comment]
建议区分国内外提供两条一键安装命令。辛苦了，感谢。

**Comment by maicong** [comment]
已经加上~ > <
