### ISSUE TITLE
debian安装后无法打开管理页面

### ISSUE THREAD

**Issue by jarvanh** [maicong/amh-4.2#2]
centos没问题，debian 6和7都无法打开

**Comment by maicong** [comment]
- \- 貌似有点问题，你先用着原版，我瞅瞅

**Comment by Jarvanh** [comment]
centos没问题，debian 6和7都不行

**Comment by maicong** [comment]
要死要死要死要死，终于有时间把它给修复了..........

**Comment by Jarvanh** [comment]
要死要死要死要死，我都等到海枯石烂了。我现在去测试一下
