### ISSUE TITLE
能否优化一下硬盘占用

### ISSUE THREAD

**Issue by jarvanh** [maicong/amh-4.2#3]
能否优化一下硬盘占用，5G的硬盘都不够安装呢

![1](http://i.imgur.com/I6jbnGI.jpg)

![Imgur](http://i.imgur.com/heLjlAB.jpg)

**Comment by maicong** [comment]
![](http://ww3.sinaimg.cn/large/67f51f75gw1erwnuu2gscj20h6052jt4.jpg)

ngx_pagespeed 占用的尺寸有点大啊。。。已经是最大限度压缩了。。。

**Comment by Jarvanh** [comment]
619M，啊，还有4.5g 空间都不够安装 =.=

**Comment by maicong** [comment]
如果 /home 是单独挂载的话 请看下 /home 下有多大可用空间

**Comment by maicong** [comment]
:+1:
