### ISSUE TITLE
PHP能不能支持pdo odbc?

### ISSUE THREAD

**Issue by chenall** [maicong/amh-4.2#4]
如题
好像脚本里面没有编译pdo_odbc的支持，我想在PHP中使用odbc连接mssql失败，提示

> 'could not find driver'

我使用FreeTDS来连接的。

http://www.freetds.org/userguide/php.htm

另外我想使用PDO方式连接，这样比较方便。或者有没有办法在不重新编译PHP的情况下支持

**Comment by maicong** [comment]
你可以手动编译安装扩展，然后在 /etc/php.ini 里面添加 .so 的文件

**Comment by chenall** [comment]
odbc支持好像需要在编译的时候加上，测试了添加这些so文件，也不行。
