### ISSUE TITLE
安装的时候出现错误

### ISSUE THREAD

**Issue by chenall** [maicong/amh-4.2#5]
log文件在这里了
http://pan.baidu.com/s/1Ap7R4

过程，本来是直接安装AMH5.0的，装完才发现是要收费的，所以就删除掉5.0，重新装官方4.2的，提示出错。

后面在网上找了下，找到了你的这个版本，先UNINSTALL 4.2再安装成功。

后面发现PHP不支持pdo-odbc，所以又删除了，在amh-mc.sh脚本的编译php处添加了--with-iodbc=/usr/local这个参数。

重新安装，失败，我以为是我修改的问题，就再次删除，直接用你给的原版和脚本，再次安装还是失败。

希望您有空可以看一下，谢谢！

**Comment by maicong** [comment]
您的服务器是 Ubuntu 64Bit，能告诉我具体什么版本吗

**Comment by chenall** [comment]
从官网下载的装在虚拟机里面

 Ubuntu 14.04.2 LTS (GNU/Linux 3.16.0-37-generic x86_64)
uname -a 的信息

```
Linux ubuntu 3.16.0-37-generic #51~14.04.1-Ubuntu SMP Wed May 6 15:23:14 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by maicong** [comment]
安装完成后，这样编译看看：

```
apt-get remove libodbc1 unixodbc unixodbc-dev -y
apt-get install php5-odbc -y
wget ftp://ftp.unixodbc.org/pub/unixODBC/unixODBC-2.3.2.tar.gz
tar -zxvf unixODBC-2.3.2.tar.gz
cd unixODBC-2.3.2
./configure --disable-gui --disable-drivers --enable-iconv --with-iconv-char-enc=UTF8 --with-iconv-ucode-enc=UTF16LE
make && make install
ldconfig;
cd /root/php-5.6.8/ext/pdo_odbc/
/usr/local/php/bin/phpize
./configure --with-pdo-odbc=unixODBC,/usr/local --with-php-config=/usr/local/php/bin/php-config;
make && make install
amh php reload
amh nginx restart
```

**Comment by maicong** [comment]
下载php 5.6.8 解压到 root 目录

**Comment by chenall** [comment]
只是现在amh安装还是失败。我现在再安装看看

**Comment by chenall** [comment]
现在全清了一下重新安装AMH，成功了，我再试试上面pdo-odbc的方法，谢谢。

**Comment by chenall** [comment]
您好，使用前面的方法编译了之后在命令行下php xxxx.test测试可以，但在amh里面测试失败"could not find driver"是不是还有什么PHP的配置文件需要修改，我已经在/etc/php.d/添加一个pdo_odbc.ini文件，里面就一行

```
extension=pdo_odbc.so
```

**Comment by chenall** [comment]
不知是什么原因，一直是这样，现在把整个系统重新之后再安装AMH，再按上面的方法加入PDO_ODBC的支持，目前正常了，很奇怪。。

谢谢！
