### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by huyx1501** [maicong/amh-4.2#8]
tar -xf ams-1.5.0107-02.tar.gz ing...
[OK] ams-1.5.0107-02 install completed.
Sorry, Failed to install AMH
Please contact us: https://github.com/maicong/amh-4.2/issues

**Comment by huyx1501** [comment]
截取了部分错误日志：
checking whether mhash >= 0.8.15... no
configure: error: "You need at least libmhash 0.8.15 to compile this program. http://mhash.sf.net/"
make: **\* No targets specified and no makefile found.  Stop.

/home/amh_install/packages/untar/php-5.6.9/sapi/cli/php: error while loading shared libraries: libltdl.so.3: cannot open shared object file: No such file or directory
make: **\* [ext/phar/phar.php] Error 127
Generating phar.phar
/home/amh_install/packages/untar/php-5.6.9/sapi/cli/php: error while loading shared libraries: libltdl.so.3: cannot open shared object file: No such file or directory
make: **\* [ext/phar/phar.phar] Error 127
Generating phar.phar
/home/amh_install/packages/untar/php-5.6.9/sapi/cli/php: error while loading shared libraries: libltdl.so.3: cannot open shared object file: No such file or directory
make: **\* [ext/phar/phar.phar] Error 127
cp: cannot create regular file `/usr/local/php/etc/php-fpm.conf': No such file or directory
cp: cannot create regular file`/usr/local/php/etc/php-fpm-template.conf': No such file or directory
mkdir: cannot create directory `/usr/local/php/etc/fpm': No such file or directory
mkdir: cannot create directory`/usr/local/php/var/run/pid': No such file or directory
touch: cannot touch `/usr/local/php/etc/fpm/amh.conf': No such file or directory
amh-mc.sh: line 620: /usr/local/php/sbin/php-fpm: No such file or directory
sed: can't read /usr/local/php/etc/php-fpm.conf: No such file or directory
sed: can't read /usr/local/php/etc/php-fpm.conf: No such file or directory
sed: can't read /usr/local/php/etc/php-fpm.conf: No such file or directory
sed: can't read /usr/local/php/etc/php-fpm.conf: No such file or directory
[OK] php-5.6.9 install completed.

怀疑是ldconfig的问题，但是手动执行ldconfig -v 发现库是存在的
[root@localhost AMH4.2-MC]# ldconfig -v |more
ldconfig: Can't stat /usr/local/libunwind/lib: No such file or directory  
ldconfig: Can't stat /usr/local/mysql/lib/mysql: No such file or directory  #这两条错误的路径不确定是不是也和AMH有关，待查证

/usr/local/lib:
        libmcrypt.so.4 -> libmcrypt.so.4.4.8
        libltdl.so.3 -> libltdl.so.3.1.0   #存在
        libmhash.so.2 -> libmhash.so.2.0.1  #存在
/usr/local/gperftools/lib:
        libprofiler.so.0 -> libprofiler.so.0.4.5
        libtcmalloc_and_profiler.so.4 -> libtcmalloc_and_profiler.so.4.2.6
        libtcmalloc.so.4 -> libtcmalloc.so.4.2.6
        libtcmalloc_debug.so.4 -> libtcmalloc_debug.so.4.2.6
        libtcmalloc_minimal.so.4 -> libtcmalloc_minimal.so.4.2.6
        libtcmalloc_minimal_debug.so.4 -> libtcmalloc_minimal_debug.so.4.2.6
/usr/local/pcre/lib:
        libpcre.so.1 -> libpcre.so.1.2.4
        libpcrecpp.so.0 -> libpcrecpp.so.0.0.1
        libpcreposix.so.0 -> libpcreposix.so.0.0.3
/usr/local/zlib/lib:
        libz.so.1 -> libz.so.1.2.8
/usr/lib/mysql:
        libmysqlclient_r.so.16 -> libmysqlclient_r.so.16.0.0
        libmysqlclient.so.16 -> libmysqlclient.so.16.0.0

# 

于是手工重新编译mcrypt和PHP，全部成功，安装完成后能进入面板了，但是不明白为什么安装脚本就会编译不成功呢？

**Comment by huyx1501** [comment]
ldconfig: Can't stat /usr/local/libunwind/lib: No such file or directory
这条错误是由于脚本中：
 echo "/usr/local/libunwind/lib" >> /etc/ld.so.conf.d/local.conf;
而libunwind是在64位系统中才安装的，所以会不存在，加入到上一句的if [ "$SysBit" == '64' ] ; then判断下面就可以了。

# 

ldconfig: Can't stat /usr/local/mysql/lib/mysql: No such file or directory
这条是官方版都会存在的错误，因为 /usr/local/mysql/lib/mysql 本来就不存在，似乎是下面的链接语句写反了
        if [ "$SysBit" == '64' ] ; then
            ln -s /usr/local/mysql/lib/mysql /usr/lib64/mysql;
        else
            ln -s /usr/local/mysql/lib/mysql /usr/lib/mysql;
        fi;

应该是：
        if [ "$SysBit" == '64' ] ; then
            ln -sf /usr/lib64/mysql /usr/local/mysql/lib/mysql ;
        else
            ln -sf /usr/lib/mysql /usr/local/mysql/lib/mysql ;
        fi;
才不会有错。

最后，在安装mcrypt前我加了句 ldconfig -v  后就安装成功了

**Comment by maicong** [comment]
= =.

**Comment by huyx1501** [comment]
原来作者还在啊。呵呵，以后会多来找你麻烦的~
